name: Schedule Check Server

on:
  schedule:
    - cron: '*/1 * * * *' # প্রতি মিনিটে চালানো হবে

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Function
        run: curl -X GET https://1min-request-sender.vercel.app/api/check_server
